### ISSUE TITLE
I would like to obtain the dataset or checkpoint train of your work

### ISSUE THREAD

**Issue by thiagomonteles** [XZhang00/QSTR#1]
Hi, I'm a student and I wanted to test your model, but the dataset is not available in the link. If you could provide me with a copy of data or the workout checkpoint, I would greatly appreciate it.

**Comment by XZhang00** [comment]
Ok, I will provide a new link as soon as possible.

**Comment by XZhang00** [comment]
https://drive.google.com/file/d/1fovvaKD6N2FssVl1lCsS-NrnI8mmygah/view?usp=drive_link

Hi, this is the new link.

**Comment by thiagomonteles** [comment]
thank you for your availability

**Comment by thiagomonteles** [comment]
Hi, when I ran the fast-train-roberta.py file with bash fast-train-roberta.sh, I noticed that some parameters like src_random_parse_path require a folder called /save4train-1W in the data. However, the data provided does not contain this information, can you tell me if this can be worked around or is there any solution for this?

**Comment by XZhang00** [comment]
Hi, "save4train-1W/src_random.tree", "save4test-1W/src_random.tree", or "save4val-1W/src_random.tree" are the randomly selected templates from the template library for each input sentence in train/test/val set. You can set $select_num to control the number of templates for each input sentence. 
After obtaining these templates, you can use the AESOP model or the SISCP model to generate paraphrases "train/pgs.txt" by inputting "train/src.txt & save4train-1W/src_random.tree", then you can calculate the ParaScore_ref scores "xxx/src_random.score-ref015" by inputting "xx/pgs.txt & xx/ref.txt".
These files are prepared in advance for quick training, and you can also prepare the data you need while training, but you need to make some changes to the code.
